--——————————————————————人物相关 
--选择界面的描述
STRINGS.CHARACTER_TITLES.esctemplate = "慕斯 -- Mousse"
STRINGS.CHARACTER_NAMES.esctemplate = "Mousse"
STRINGS.CHARACTER_DESCRIPTIONS.esctemplate = "*有升级系统\n*初始携带绒球*\n是个可爱猫猫"
STRINGS.CHARACTER_QUOTES.esctemplate = "\"你好......请、请叫我慕斯......那个，我的手，请您不要盯着我的手看......\""


--————————————————————物品名称，描述等字符串————————————————————————————————————————
STRINGS.TABS.SAMANSHA = "苏曼莎专属"
--鹿
STRINGS.NAMES.SA_DEER = "鹿"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SA_DEER = "真漂亮"

--眼罩
STRINGS.NAMES.HAT_EYESHADE = "眼罩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_EYESHADE = "这是一团纱布？！"
STRINGS.RECIPE_DESC.HAT_EYESHADE = "夜视"
--鹿角帽
STRINGS.NAMES.HAT_DEER = "鹿角帽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_DEER = "看起来挺吓人"
STRINGS.RECIPE_DESC.HAT_DEER = "鹿角做的帽子，温暖又结实"

--保湿帽
STRINGS.NAMES.HAT_WATER = "保湿帽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_WATER = "凉凉的很舒服"
STRINGS.RECIPE_DESC.HAT_WATER = "保持身体湿润"

--荆棘铠甲
STRINGS.NAMES.ARMOR_THORNS = "荆棘铠甲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_THORNS = "好扎人"
STRINGS.RECIPE_DESC.ARMOR_THORNS = "反伤甲,阴影之主斯布雷斯的馈赠"

--隐身衣
STRINGS.NAMES.CLOTHES_INVISIBLE = "隐身衣"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLOTHES_INVISIBLE = "摸着真轻柔"
STRINGS.RECIPE_DESC.CLOTHES_INVISIBLE = "穿上就可以隐身。"


--鹿角
STRINGS.NAMES.DEER_HORN = "鹿角"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEER_HORN = "这是……鹿角？"
--鹿心
STRINGS.NAMES.DEERHEART = "鹿心"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEERHEART = "似乎还在跳动"
STRINGS.RECIPE_DESC.DEERHEART = "鹿的心脏，有神奇功效"

--莲子
STRINGS.NAMES.LOTUS_SEED = "莲子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOTUS_SEED = "据说很好吃。"

--荷叶
STRINGS.NAMES.LOTUS_LEAF = "荷叶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOTUS_LEAF = "据说可以漂洋过海。"

--荷花
STRINGS.NAMES.LOTUS_FLOWER = "荷花"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOTUS_FLOWER = "苏曼莎知道它们生长情况"
--荷花池
STRINGS.NAMES.LOTUS_POND = "荷花池"
STRINGS.RECIPE_DESC.LOTUS_POND = "种植荷花，出产荷叶和莲子。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOTUS_POND = {
	GENERIC = "真是个漂亮的池塘",
	NEEDSFERTILIZER = "似乎肥料不够了",
}
--荷叶伞
STRINGS.NAMES.LOTUS_UMBRELLA = "荷叶伞"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOTUS_UMBRELLA = "能吃吗？"
STRINGS.RECIPE_DESC.LOTUS_UMBRELLA = "荷叶做的雨伞"


--望远镜
STRINGS.NAMES.TELESCOPE = "望远镜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TELESCOPE = "在动手之前要仔细观察"
STRINGS.RECIPE_DESC.TELESCOPE = "观察目标动向"

--荷花心经
STRINGS.NAMES.LOTUS_BOOK = "荷花心经"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOTUS_BOOK = "只有苏曼莎知道如何使用这本书"

-------------技能------------------
STRINGS.ACTIONS.SA_BOOK = {
	GENERIC = "思考",
	TWISTER_OFF = "停止",
	TWISTER_ON = "扶摇直上",
	HARVERST = "五谷丰登",
	PHOTOSYNTHESIS_ON = "光合",
	PHOTOSYNTHESIS_OFF = "停止",
}

STRINGS.CHARACTERS.GENERIC.BACKSTAB = {
	SUCCESS = "吓！",
	FAILED = "啊呀……",
}